# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "99c3e4b055530a8caf0f2979ad86554f"
name = "warranty-info"
handle = "warranty-info"
application_url = "https://biol-castle-told-graphs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bicycle-shop-stephenie.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://biol-castle-told-graphs.trycloudflare.com/auth/callback",
  "https://biol-castle-told-graphs.trycloudflare.com/auth/shopify/callback",
  "https://biol-castle-told-graphs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
